language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: CRFEntityExtractor
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 90
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150
#  - name: LexicalSyntacticFeaturizer
#  - name: CRFEntityExtractor
#  - name: EntitySynonymMapper
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 150
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.25
    ambiguity_threshold: 0.1
    core_threshold: 0.25
    fallback_action_name: 'action_default_fallback'
#  - name: TwoStageFallbackPolicy 
#  - name: KerasPolicy
#    max_history: 5
#    epochs: 200
#    validation_split: 0.15
#    random_seed: 1
